apiVersion: apps/v1
kind: Deployment
metadata:
  name: duhiguree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duhiguree
  template:
    metadata:
      labels:
        app: duhiguree
    spec:
      containers:
        - name: duhiguree
          image: duhiguree:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3007