apiVersion: apps/v1
kind: Deployment
metadata:
  name: duhigure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duhigure
  template:
    metadata:
      labels:
        app: duhigure
    spec:
      containers:
        - name: duhigure
          image: duhigure:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
